config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"

  get 'tag_search', to: 'books#tag_search', as: 'tag_search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
      get :date_books
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :chat_rooms do
    resources :direct_messages, only: [:create]
  end

  resources :groups do
    resources :group_users, only: [:create, :destroy]
    member do
      get :new_event_notice
      post :send_event_notice
      get :sent_event_notice
    end
  end
  get "search", to: "searches#search", as: "search"

  resources :notifications, only:[:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only:[:show, :edit, :update, :destroy]
  before_action :ensure_owner, only:[:edit, :update, :destroy]


  def index
    @groups = Group.all
  end

  def show
  end

  def edit
  end

  def update
    if @group.updeta(group_params)
      flash[:notice] = "Group was successfully updated."
      redirect_to @group
    else
      render :edit
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.owned_groups.build(group_params)
    if @group.save
      @group.group_users.create(user: current_user)
      flash[:notice] = "Group was successfully created."
      redirect_to groups_path
    else
      render :new
    end
  end

  def destroy
    @group.destroy
    flash[:notice] = "Group was deleted!"
    redirect_to groups_path
  end

  def new_event_notice
    @group = Group.find(params[:id])
  end

  def send_event_notice
    @group = Group.find(params[:id])
    @subject = params[:subject]
    @content = params[:content]
    EventMailer.event_notice_email(@group, @subject, @content).deliver_now
    redirect_to sent_event_notice_group_path(@group, subject: @subject, content: @content)
  end

  def sent_event_notice
    @group = Group.find(params[:id])
    @subject = params[:subject]
    @content = params[:content]
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def ensure_owner
    redirect_to group_path, alert: "You are not authorized to edit this group." unless @group.owner == current_user
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h2>Edit Group</h2>
<%= form_with(model: @group, local: true) do |form| %>
  <label>グループ名</label>
  <%= form.text_field :name %>
  <label>紹介文</label>
  <%= form.text_area :introduction %>
  <label>グループ画像</label>
  <%= form.file_field :image %>
  <%= form.submit %>
<% end %>

app/views/groups/index.html.erb
<h2>Groups</h2>

<table class = "table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
    <tr>
      <td><%= image_tag group.get_group_image, size: "50x50" %></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= group.introduction %></td>
      <td><%= group.group_users.count %></td>
      <td>
        <% if group.owner == current_user %>
          <%= link_to "Edit", edit_group_path(group), class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h2>Create Group</h2>
<%= form_with(model: @group, local: true) do |form| %>
  <label>グループ名</label>
  <%= form.text_field :name %>
  <label>紹介文</label>
  <%= form.text_area :introduction %>
  <label>グループ画像</label>
  <%= form.file_field :group_image %>
  <%= form.submit %>
<% end %>

app/views/groups/new_event_notice.html.erb
<div class = "container">
  <div class = "row justify-content-center" >
    <div class = "col-7">
      <h2>Event Mail</h2>
      <%= form_with url: send_event_notice_group_path(@group), method: :post do |f| %>
      <div>
        <p>Title</p>
        <%= f.text_field :subject, style: "width: 100%;" %>
      </div>
      <div>
        <p class = "mt-3">Content</p>
        <%= f.text_area :content, style: "width: 100%;" %>
      </div>
      <div class = "d-flex justify-content-end mt-3 " >
        <%= f.submit "送信", class: " btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/sent_event_notice.html.erb
<div class = "container">
  <div class = "row justify-content-center" >
    <div class = "col-7">
      <h2>送信が完了しました。</h2>
      <p>内容は以下の通り</p>
      <div>
        <p>Title</p>
        <%= @subject %>
      </div>
      <div>
        <p class = "mt-3">Content</p>
        <%= @content %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<h2>Group Detail</h2>
<table class = "table">
  <tr>
    <td><%= image_tag @group.get_group_image, size: "50x50" %></td>
    <td><%= @group.name %></td>
    <td><%= @group.introduction %></td>
    <td>
    <% @group.group_users.each do |group_user| %>
      <div><%= group_user.user.name %></div>
    <% end %>
    </td>
    <td>
      <% if @group.owner == current_user %>
        <%= link_to "Edit", edit_group_path, class: "btn btn-primary" %> /
        <%= link_to "Destroy", group_path(@group), method: :delete, class: "btn btn-danger" %> /
        <%= link_to "Notice an Event", new_event_notice_group_path(@group), class: "btn btn-primary" %>
      <% end %>
      <% if @group.owner != current_user && !@group.group_users.exists?(user_id: current_user) %>
        <%= link_to "Join this group", group_group_users_path(@group), method: :post, class: "btn btn-success" %>
      <% elsif @group.group_users.exists?(user_id: current_user) %>
        <%= link_to "Leave this group", group_group_user_path(@group, current_user), method: :delete, class: "btn btn-danger" %>
      <% end %>
    </td>
  </tr>
</table>