config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"

  get 'tag_search', to: 'books#tag_search', as: 'tag_search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
      get :date_books
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :chat_rooms do
    resources :direct_messages, only: [:create]
  end

  resources :groups do
    resources :group_users, only: [:create, :destroy]
    member do
      get :new_event_notice
      post :send_event_notice
      get :sent_event_notice
    end
  end
  get "search", to: "searches#search", as: "search"

  resources :notifications, only:[:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # bookers2基本機能
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # フォロー・フォロワー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def mutual_follow?(other_user)
    self.following?(other_user) && other_user.following?(self)
  end
  
  # グループ機能
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users
  
  # 通知機能
  has_many :notifications, dependent: :destroy
  

  
  def todays_books_count
    books.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end

  def books_from_yesterday_count
    books.where(created_at: 1.day.ago.all_day).count
  end

  def boos_day_over_day_change
    today_count = todays_books_count

    yesterday_count = books_from_yesterday_count

    return "No date for yesterday" if yesterday_count == 0

    change_ratio = ((today_count - yesterday_count).to_f / yesterday_count) * 100

    "#{change_ratio.round(0)}%"

  end

  def books_from_this_week_count
    start_of_week = Time.zone.now.beginning_of_week(:saturday)
    books.where(created_at: start_of_week..Time.zone.now.end_of_day).count
  end

  def books_from_last_week_count
    start_of_last_week = 1.week.ago.beginning_of_week(:saturday)
    end_of_last_week = start_of_last_week + 6.days
    books.where(created_at: start_of_last_week..end_of_last_week.end_of_day).count
  end

  def books_week_over_week_change
    this_week_count = books_from_this_week_count
    last_week_count = books_from_last_week_count

    return "No data for last week" if last_week_count == 0

    change_ratio = ((this_week_count - last_week_count).to_f / last_week_count) * 100
    "#{change_ratio.round(0)}%"
  end
  
  def books_count_last_7_days
    (6.downto(0)).map do |i|
      day = i.days.ago.to_date
      { days_ago: i, count: books.where(created_at: day.beginning_of_day..day.end_of_day).count }
    end
  end 
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :set_user, only: [:show, :following, :followers]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
    @title = "Follow Users"
    @users = @user.following
    render "show_follow"
  end

  def followers
    @title = "Follower Users"
    @users = @user.followers
    render "show_follow"
  end

  def date_books
    @user = User.find(params[:id])
    @selected_date = params[:selected_date].to_date
    @books_count = @user.books.where(created_at: @selected_date.all_day).count

    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.following.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <% if current_user.following?(user) %>
        <td><%= link_to "フォロー外す", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete, class: "btn btn-primary" %></td>
        <% else %>
        <td><%= link_to "フォローする", relationships_path(followed_id: user.id), method: :post, class: "btn btn-success" %></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to user.following.count, following_user_path(user) %></th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
  <% if user != current_user %>
  <tr>
    <% if current_user.following?(user) %>
    <th style="border: none;">
      <%= link_to "フォロー外す", relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete, class: "btn btn-primary" %>
    </th>
    <% else %>
    <th style="border: none;">
      <%= link_to "フォローする", relationships_path(followed_id: user.id), method: :post, class: "btn btn-success" %>
    </th>
    <% end %>
    <% if current_user.mutual_follow?(user) %>
    <th style="border: none;">
      <%= link_to "DM", chat_room_path(ChatRoom.find_or_create_by_users(current_user, user)), class: "btn btn-outline-primary" %>
    </th>
    <% end %>
  </tr>
  <% end %>
  <tr>
  <% if user == current_user %>
    <th><%= link_to "DM List", chat_rooms_path, class: "btn btn-outline-primary" %></th>
    <th></th>
  <% end %>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/date_books.js.erb
document.getElementById('book-count').innerHTML = `
  <h3 class = "mt-2">検索結果</h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @books_count %> 件</td>
      </tr>
    </tbody>
  </table>
`;

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "Create Group", new_group_path %>/<%= link_to "Groups", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h3>Books</h3>
      <%= render 'books/index',books: @books %>
      <h3>投稿数の前日比・前週比</h3>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th style="width: 33%;">今日の投稿数</th>
            <th style="width: 33%;">前日の投稿数</th>
            <th style="width: 34%;">前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @user.todays_books_count %></td>
            <td><%= @user.books_from_yesterday_count %></td>
            <td><%= @user.boos_day_over_day_change %></td>
          </tr>
        </tbody>
      </table>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th style="width: 33%;">今週の投稿数</th>
            <th style="width: 33%;">前週の投稿数</th>
            <th style="width: 34%;">前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @user.books_from_this_week_count %></td>
            <td><%= @user.books_from_last_week_count %></td>
            <td><%= @user.books_week_over_week_change %></td>
          </tr>
        </tbody>
      </table>
      <table class = "table table-bordered">
        <thead>
          <tr>
            <% @user.books_count_last_7_days.each do |day_date| %>
              <% if day_date[:days_ago] == 0 %>
              <th>今日</th>
              <% else %>
              <th><%= "#{day_date[:days_ago]}日前" %></th>
              <% end %>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @user.books_count_last_7_days.each do |day_count| %>
              <td><%= day_count[:count] %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div>
        <p class = "text-center">７日間の投稿数の比較</p>
        <canvas id="postsChart"></canvas>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
          document.addEventListener('DOMContentLoaded', function() {
            var ctx = document.getElementById('postsChart').getContext('2d');
            var postsChart = new Chart(ctx, {
              type: 'line', // グラフの種類
              data: {
                labels: ["6日前", "5日前", "4前", "3日前", "2日前", "1日前", "今日"],
                datasets: [{
                  label: '比較した本の数',
                  data: <%= raw(@user.books_count_last_7_days.map { |day_data| day_data[:count] }.to_json) %>, // Y軸のデータ
                  backgroundColor: 'rgba(54, 162, 235, 0.2)',
                  borderColor: 'rgba(54, 162, 235, 1)',
                  borderWidth: 1,
                  tension: 0.4
                }]
              },
              options: {
                scales: {
                  y: {
                    beginAtZero: true,
                    min: 0, // Y軸の最小値を0に設定
                    max: 10, // Y軸の最大値を10に設定
                    ticks: {
                      stepSize: 1 // Y軸の目盛りを1刻みに設定
                    }
                  }
                }
              }
            });
          });
        </script>





      </div> <!--グラフのコード-->
      <div class = "mt-5">
        <%= form_with url: date_books_user_path(@user), method: :get, local: false do |f| %>
        <div class = "d-flex">
          <%= f.date_field :selected_date, class: "form-control", placeholder: "日付を選択", style: "width: 30%;" %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
      <div id = "book-count"></div>

    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<h2><%= @title %></h2>
<table class="table">
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td>
      <%= image_tag user.get_profile_image, size: "50x50" %>
    </td>
    <td>
      <%= user.name %>
    </td>
    <td>
      フォロー数:<%= user.following.count %>
    </td>
    <td>
      フォロワー数:<%= user.followers.count %>
    </td>
    <td>
      <%= link_to "Show", user_path(user) %>
    </td>
  </tr>
  <% end %>
</table>