config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"

  get 'tag_search', to: 'books#tag_search', as: 'tag_search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
      get :date_books
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :chat_rooms do
    resources :direct_messages, only: [:create]
  end

  resources :groups do
    resources :group_users, only: [:create, :destroy]
    member do
      get :new_event_notice
      post :send_event_notice
      get :sent_event_notice
    end
  end
  get "search", to: "searches#search", as: "search"

  resources :notifications, only:[:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @model = params[:model]
    @search_method = params[:search_method]
    @query = params[:query]
    
    if @model == "user"
      @results = search_for_user(@search_method, @query) || []
    elsif @model == "book"
      @results = search_for_book(@search_method, @query) || []
    else
      @results = []
    end 
  end
  
  private
  
  def search_for_user(search_method, query)
    case search_method
    when "perfect"
      User.where(name: query)
    when "forward"
      User.where("name LIKE ?", "#{query}%")
    when "backward"
      User.where("name LIKE ?", "%#{query}")
    when "partial"
      User.where("name LIKE ?", "%#{query}%")
    end
  end

  def search_for_book(search_method, query)
    case search_method
    when "perfect"
      Book.where(title: query)
    when "forward"
      Book.where("title LIKE ?", "#{query}%")
    when "backward"
      Book.where("title LIKE ?", "%#{query}")
    when "partial"
      Book.where("title LIKE ?", "%#{query}%")
    end
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<% if @model == "user" %>
  <h2>Users search for "<%= @query %>"</h2>
<% elsif @model == "book" %>
  <h2>Books search for "<%= @query %>"</h2>
<% end %>

<table class = "table">
  <tr>
    <% if @model == "user" %>
    <th></th>
    <th>Name</th>
    <th>Introduction</th>
    <% elsif @model == "book" %>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <% end %>
  </tr>
  <% if @results.any? %>
    <% @results.each do |result| %>
      <% if @model == "user" %>
      <td>
        <%= image_tag result.get_profile_image, size:'50x50' %>
      </td>
      <td>
        <%= link_to result.name, user_path(result) %>
      </td>
      <td>
        <%= result.introduction %>
      </td>
      <% elsif @model == "book" %>
      <td>
        <%= image_tag result.user.get_profile_image, size:'50x50' %>
      </td>
      <td>
        <%= link_to result.title, book_path(result) %>
      </td>
      <td>
        <%= result.body %>
      </td>
      <% end %>
    <% end %>
  <% else %>
    <p>該当する結果がありませんでした。</p>
  <% end %>
</table>