config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"

  get 'tag_search', to: 'books#tag_search', as: 'tag_search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following, :followers
      get :date_books
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :chat_rooms do
    resources :direct_messages, only: [:create]
  end

  resources :groups do
    resources :group_users, only: [:create, :destroy]
    member do
      get :new_event_notice
      post :send_event_notice
      get :sent_event_notice
    end
  end
  get "search", to: "searches#search", as: "search"

  resources :notifications, only:[:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  acts_as_taggable_on :tags

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  scope :popular, -> {
    left_joins(:favorites)
      .group("books.id")
      .order("COUNT(favorites.id) DESC")
  }

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end  

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :direct_messages, dependent: :destroy

  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  def other_user(current_user)
    user1 == current_user ? user2 : user1
  end
  
  def self.find_or_create_by_users(user1,user2)
    user1, user2 = [user1, user2].sort_by(&:id)
    chat_room = ChatRoom.find_by(user1: user1, user2: user2)
    chat_room ||= ChatRoom.create(user1: user1, user2: user2)
    chat_room
  end

end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_one :notification, as: :notifiable, dependent: :destroy
  
  validates :user_id, uniqueness: {scope: :book_id}
  
  after_create do
    create_notification(user_id: book.user_id)
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # bookers2基本機能
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # フォロー・フォロワー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def mutual_follow?(other_user)
    self.following?(other_user) && other_user.following?(self)
  end
  
  # グループ機能
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users
  
  # 通知機能
  has_many :notifications, dependent: :destroy
  

  
  def todays_books_count
    books.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end

  def books_from_yesterday_count
    books.where(created_at: 1.day.ago.all_day).count
  end

  def boos_day_over_day_change
    today_count = todays_books_count

    yesterday_count = books_from_yesterday_count

    return "No date for yesterday" if yesterday_count == 0

    change_ratio = ((today_count - yesterday_count).to_f / yesterday_count) * 100

    "#{change_ratio.round(0)}%"

  end

  def books_from_this_week_count
    start_of_week = Time.zone.now.beginning_of_week(:saturday)
    books.where(created_at: start_of_week..Time.zone.now.end_of_day).count
  end

  def books_from_last_week_count
    start_of_last_week = 1.week.ago.beginning_of_week(:saturday)
    end_of_last_week = start_of_last_week + 6.days
    books.where(created_at: start_of_last_week..end_of_last_week.end_of_day).count
  end

  def books_week_over_week_change
    this_week_count = books_from_this_week_count
    last_week_count = books_from_last_week_count

    return "No data for last week" if last_week_count == 0

    change_ratio = ((this_week_count - last_week_count).to_f / last_week_count) * 100
    "#{change_ratio.round(0)}%"
  end
  
  def books_count_last_7_days
    (6.downto(0)).map do |i|
      day = i.days.ago.to_date
      { days_ago: i, count: books.where(created_at: day.beginning_of_day..day.end_of_day).count }
    end
  end 
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Notification
              <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% if current_user.notifications.where(read: false).any? %>
                <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                  <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                <% end %>
              <% else %>
                <span class="dropdown-item disabled">未読の通知はありません</span>
              <% end %>
            </div>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
      </div>
    </div>
  </nav>
  <div class="d-flex justify-content-center mt-4">
    <div>
      <% if user_signed_in? %>
        <%= form_with url: search_path, method: :get, local: true do %>
          <%= text_field_tag :query, params[:query], placeholder: "検索ワードを入力" %>
          <%= select_tag :model, options_for_select([["User", "user"],["Book", "book"]]), prompt: "検索対象を選択" %>
          <%= select_tag :search_method, options_for_select([["完全一致", "perfect"],["前方一致", "forward"],["後方一致", "backward"],["部分一致", "partial"]]), prompt: "検索方法を選択" %>
          <%= submit_tag "検索" %>
        <% end %>
        <%= form_with url: tag_search_path, method: :get, local: true do %>
          <%= label_tag :tag, "タグで検索" %>
          <%= text_field_tag :tag, params[:tag], placeholder: "タグを入力" %>
          <%= submit_tag "検索", class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/7b2eb5666f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>